name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Classic Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.PROFILE }}
          committer_token: ${{ secrets.PROFILE }}
          committer_branch: main
          base: header, repositories
          plugin_lines: yes

      - name: Generate Language Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.PROFILE }}
          committer_token: ${{ secrets.PROFILE }}
          committer_branch: main
          base: ""
          template: classic
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, bytes-size
          plugin_languages_threshold: 2%
          plugin_languages_other: yes
